name: Code Review BOT

permissions:
  # Allows the workflow to read repository contents
  contents: read

  # Allows the workflow to create, update, or comment on pull requests
  pull-requests: write

on:
  pull_request:
    # Triggers on these pull request events:
    # - opened: When a new pull request is created
    # - synchronize: When new commits are pushed to the pull request's branch
    # - reopened: When a previously closed pull request is reopened
    # - ready_for_review: When a draft pull request is marked as ready for review
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
    - uses: anc95/ChatGPT-CodeReview@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MODEL: gpt-5-nano